title: Jinbo # your site title
author: Jinbo
email:  jinboom@foxmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Python/C/C++ developer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jinbooooom.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:  jinbooooom # replace with your_github_username or comment to remove link from footer
instagram_username: # replace with your_instagram_username or comment to remove link from footer
social:
  name: 
  links:
    #- https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    #- https://www.linkedin.com/in/BenBalter
    #- https://plus.google.com/+BenBalter
    #- https://github.com/jinbooooom
    #- https://keybase.io/benbalter

disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
#theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
